version: "3.8"

services:
  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - django_chat_net

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    networks:
      - django_chat_net

  api:
    container_name: api
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/api
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - django_chat_net

  # socket:
  #   container_name: c_budget
  #   build: ./socket
  #   command: npm run dev
  #   stdin_open: true
  #   volumes:
  #     - ./c_budget:/usr/src/c_budget
  #     - /usr/src/c_budget/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  #   networks:
  #     - django_chat_net

  # front:
  #   container_name: c_front
  #   build: ./front

volumes:
  postgres_data:

networks:
  django_chat_net:
    driver: bridge
