# Generated by Django 4.0 on 2022-01-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_from',
        ),
        migrations.AddField(
            model_name='comments',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='auth.user'),
            preserve_default=False,
        ),
    ]
